version: '3'
services:
  cfddns:
    container_name: cfddns
    restart: 'unless-stopped'
    security_opt:
      - no-new-privileges:true
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - CF_IPV4_RECORD=${CF_IPV4_RECORD}
      - CF_RECORD_TYPE=${CF_RECORD_TYPE}
      - CF_PROXIED=${CF_PROXIED}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - CF_API_TOKEN=${CF_API_TOKEN}
        - CF_ZONE_ID=${CF_ZONE_ID}
        - CF_IPV4_RECORD=${CF_IPV4_RECORD}
        - CF_RECORD_TYPE=${CF_RECORD_TYPE}
        - CF_PROXIED=${CF_PROXIED}
